sudo: required

services:
  - docker

language: go

script:
  - set -e
  - test -e ca-certificates.crt || {
      docker run -v $(pwd):/data -t --rm ubuntu:17.04 bash -c \
        'apt-get update -qqy && apt-get install ca-certificates coreutils -qqy && /bin/cp /etc/ssl/certs/ca-certificates.crt /data';
    }
  - go get github.com/PuerkitoBio/goquery &&
    go get github.com/hoisie/redis &&
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  - docker build -t hubmon .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - echo '---------' && env && echo '--------------'
  - echo "Pushing hubmon:$TRAVIS_BRANCH or hubmon:$TRAVIS_TAG"
  - case "$TRAVIS_BRANCH" in
      dev )
          docker tag hubmon:latest $DOCKER_USERNAME/hubmon:dev;
          docker push $DOCKER_USERNAME/hubmon:dev
        ;;
      master )
          docker tag hubmon:latest $DOCKER_USERNAME/hubmon:latest;
          docker push $DOCKER_USERNAME/hubmon:latest
        ;;
    esac
  - case "$TRAVIS_TAG" in
      v[0-9]* )
          tag="$(echo $TRAVIS_TAG | cut -c2-)";
          docker tag hubmon:latest $DOCKER_USERNAME/hubmon:$tag;
          docker push $DOCKER_USERNAME/hubmon:$tag
        ;;
    esac
