sudo: required

services:
  - docker

language: go

env:
  global:
    - NS_NAME=bvberkum
    - APP_ID=x-docker-hub-build-monitor
    - APP_BIN=hubmon
    - BUILD_GOARCH="386 amd64" 
    - BUILD_GOOS="linux" 
    - DO_GITHUB_DEPLOY=1

script:
  - . ./cert-init.sh
  - docker run --rm
    -e CGO_ENABLED=true
    -e COMPRESS_BINARY=true
    -e BUILD_GOOS="$BUILD_GOOD"
    -e BUILD_GOARCH="$BUILD_GOARCH"
    -v "$(pwd -P):/src"
    -v /var/run/docker.sock:/var/run/docker.sock
    centurylink/golang-builder-cross $APP_ID:local

test:
  - ./hooks/test

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - echo '---------' && env && echo '--------------'
  - echo "Pushing $APP_ID:$TRAVIS_BRANCH or $APP_ID:$TRAVIS_TAG"
  - case "$TRAVIS_BRANCH" in
      dev )
          docker tag $APP_ID:local $DOCKER_USERNAME/$APP_ID:dev;
          docker push $DOCKER_USERNAME/$APP_ID:dev
        ;;
      master )
          docker tag $APP_ID:local $DOCKER_USERNAME/$APP_ID:latest;
          docker push $DOCKER_USERNAME/$APP_ID:latest
        ;;
    esac
  - case "$TRAVIS_TAG" in
      v[0-9]* )
          tag="$(echo $TRAVIS_TAG | cut -c2-)";
          docker tag $APP_ID:local $DOCKER_USERNAME/$APP_ID:$tag;
          docker push $DOCKER_USERNAME/$APP_ID:$tag
        ;;
    esac

deploy:
  provider: releases
  api_key:
    secure: cpNDJo95st0v83Bds9T2N3jyrA6Zj9vDTQBaBpz/5EB3Fe/7pKI4QlATwY/wbDHpD+0Dx1DzZ5gftu0olONym7/JfZ0X1KFVit/vEsUoNv5K8lid1P+MPGJ/5mcB35yPg1Lff9EVa9hH4FnxCNeUbpox866QsSPAM5StbC3XXgX5DaLH3i8b0AH5XFzB4Rk4yygi7RGyXJZhXtCTEdNtVWVJICpx72l/bp0ShfR12vIXMQ4LCENHkpnMbgxvRCBwX8df4bX9N/MuGaR0S76OPzkX8mLXqUmUtkbWv/p60x5fui5Bbtv9X3L1pYNYwkJjfoTFF2f4aNEVJxlyhxHdiQG0hvr+44kWz1b1XbzRPqqE7f+0y3Kpnc89/DxCfrHzf7aCVT2pe0afo/DITGjZAKSLOdq1gchsxIIPY81X+CI6G66bfOlHcr/M3GvLiMdLInTZPAPk/DDY8L6MXy2fzLN3H4NBdiv+BlHUQg38JgOcnUWPMq0ACHGM1WT7DM2YIZl1r9PVoUVmGq4Jy1LC8uy23XMKId4b15gu6h61b0o1TxFIiIg2nKlL8Qr8D4x/tmaOj89+FKlulDN3VOTgKnESUYxJqMotM80EQ5UlCHw+TwFVFAK5iOFUwry0ACBb6wXdOOr73aRDmt7/vf3opNKkP0hMjdHiDsDCPJZb2lc=
  skip_cleanup: true
  file:
    - $APP_ID-linux-amd64
    - $APP_ID-linux-386
    - $APP_ID-darwin-amd64
    - $APP_ID-darwin-386
  on:
    repo: bvberkum/x-docker-hub-build-monitor
    tags: true

