sudo: required

services:
  - docker

language: go

env:
  global:
    - NS_NAME=bvberkum
    - APP_ID=hubmon
    - BUILD_GOARCH="386 amd64" 
    - BUILD_GOOS="linux" 
    - DO_GITHUB_DEPLOY=1

script:
  - . ./cert-init.sh
  - docker run --rm
    -e CGO_ENABLED=true
    -e COMPRESS_BINARY=true
    -e BUILD_GOOS="$BUILD_GOOD"
    -e BUILD_GOARCH="$BUILD_GOARCH"
    -v "$(pwd -P):/src"
    -v /var/run/docker.sock:/var/run/docker.sock
    centurylink/golang-builder-cross $APP_ID:local

test:
  - ./hooks/test

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - echo '---------' && env && echo '--------------'
  - echo "Pushing $APP_ID:$TRAVIS_BRANCH or $APP_ID:$TRAVIS_TAG"
  - case "$TRAVIS_BRANCH" in
      dev )
          docker tag $APP_ID:local $DOCKER_USERNAME/$APP_ID:dev;
          docker push $DOCKER_USERNAME/$APP_ID:dev
        ;;
      master )
          docker tag $APP_ID:local $DOCKER_USERNAME/$APP_ID:latest;
          docker push $DOCKER_USERNAME/$APP_ID:local
        ;;
    esac
  - case "$TRAVIS_TAG" in
      v[0-9]* )
          tag="$(echo $TRAVIS_TAG | cut -c2-)";
          docker tag $APP_ID:local $DOCKER_USERNAME/$APP_ID:$tag;
          docker push $DOCKER_USERNAME/$APP_ID:$tag
        ;;
    esac

deploy:
  provider: releases
  api_key:
    secure: RdNjxwdOepzUIMvCjSg8grYLWoavu48FDCELAD4i5GVOwPhvoRfiZT1fUAx5QtanYo65WjhH8b8HRjCRM9vbcw+y3co6YlCuWHZMOcUgZ0lDVRZZKsMUhdn9SJ9VlPkYwxSb6yhW93JZF/hf02t6iBb1Ln9PsBA/iH036EKca25rf8/wFZanrtUfzqTnAnzMCjQVZDKW0IU+nyhdm1TlRdnlH4+zasUOTCAWx3Zpc4AHDqAzTgLJQAdSJX6VVnHamSS3Zv5Al3uR6TQWSCIGkl9mzVKb5GWLcSVM/6MAKML4dqy/azDctbzZcclZF3p9E00xwWiyFQzi6KZ9Qy33ZL98nmBVvEIkcL76goQ1ByzcA91ym4AcRoQ29SdWzhL9FKiiJwDH8WeEj1EcFO2yAQITQpoF/Sqvs4VIytUXufKroBjy8pjNUFLMBKCjJxM8pr95WleY7xfaOql4EebGDP4xVAC9XzxbVy7rAmRmXVgAcnTK1gqtD+alcs0q9lNk8BeelVgRGArHLdhd4kaiVwDGKzbaZh6jdrRO5oNOtxfVLvlWUWAmHIl/9es0BY98KtMsab5IcU6uPkct5sJayILMCNec84nnks4pgx/629+cAtz1Q7yyd/YbYyyzNCulSoMfDaEbjAiv1XclklLXp8kQINmebrHBqdokbBABY8w=
  file:
    - $APP_ID-linux-amd64
    - $APP_ID-linux-386
    - $APP_ID-darwin-amd64
    - $APP_ID-darwin-386
  on:
    repo: bvberkum/x-docker-hub-build-monitor
    branch: dev
