sudo: required

services:
  - docker

language: go

script:
  - set -e
  - test -e ca-certificates.crt || {
      docker run -v $(pwd):/data -t --rm ubuntu:17.04 bash -c \
        'apt-get update -qqy && apt-get install ca-certificates coreutils -qqy && /bin/cp /etc/ssl/certs/ca-certificates.crt /data';
    }
  - go get github.com/PuerkitoBio/goquery &&
    go get github.com/hoisie/redis &&
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  - docker build -t hubmon .

after_success:
  - test "$TRAVIS_BRANCH" != "master"  || { 
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      echo docker push bvberkum/hubmon;
    }
