- type: application/vnd.org.wtwta.project
  bin: hubmon
  id: x-docker-hub-build-monitor
  main: x-docker-hub-build-monitor
  version: 0.0.2-dev # x-docker-hub-build-monitor
  license: MIT
  urls:
    base:
      - http://github.com/bvberkum/x-docker-hub-build-monitor
    license:
      - https://choosealicense.com/licenses/mit/
      - https://opensource.org/licenses/MIT
    source-code:
      - http://github.com/bvberkum/x-docker-hub-build-monitor.git
    images:
      - https://hub.docker.com/r/bvberkum/x-docker-hub-build-monitor
    builds:
      - https://travis-ci.org/bvberkum/x-docker-hub-build-monitor
  repositories:
    github: git@github.com:bvberkum/x-docker-hub-build-monitor.git
  scripts:
    init:
      - htd package update
      - vc regenerate
    travis-init:
      - test -x \"$(which travis)\" || gem install travis
      - . ./travis-setenv.sh
      - travis setup releases
    check:
      - verbosity=1 git-versioning check
    pre-commit:
      - make
    docs:
      - make doc
    build:
      - sh ./build.sh
    test:
      - docker-compose -phubmon build &&
        docker-compose -phubmon up -d sut &&
        docker logs -f hubmon_sut_1 &&
        docker-compose -phubmon rm --force -v
    hubmon-help:
      - docker run --rm bvberkum/hubmon -h
